### ISSUE TITLE
Supporting Crane's metric adapter as remote adapter of Prometheus Adapter

### ISSUE THREAD

**Issue by MarkyMark4120** [gocrane/crane#448]
Crane v0.6.0 supports Prometheus Adapter as remote adapter and Crane's metric adapter as the main adapter. Is there a way to do the opposite by making Crane's metric adapter as the remote adapter and Prometheus Adapter as the main adapter in the apiservice? 
The reason of asking this question is some apps are already using the custom metric adapter for HPA but installing Crane will replace the original metric adapter.

**Comment by qmhu** [comment]
We can't make Prometheus Adapter to proxy the metric requests without change its code, that's why we develop the `RemoteAdapter` feature.

If you already have develop Prometheus Adapter as your main adapter, then you can use crane's metric-adapter to be main adapter and proxy the request to Prometheus Adapter by `RemoteAdapter` feature. In this structure,  crane's metric-adapter  will provide both crane's metric and all the prometheus metrics.

The overall Architecture is like below:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/6251116/182285335-71e7ca52-fee4-4c7c-9254-1aef4fb70263.png">
