### ISSUE TITLE
Volume Plugin

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#738]
## Describe the feature

Find the Orphan Volumes in k8s cluster: List all volumes and check if it has any pod using, if not then report it.

**Comment by xiu111** [comment]
可以使用Kubernetes Volume Snapshotter。Volume Snapshotter是一个Kubernetes插件，可以将PV/PVC卷的快照备份到Kubernetes集群中的持久存储中。该插件可以通过以下步骤来实现查找和报告孤立卷：

使用Kubernetes Volume Snapshotter创建PV/PVC卷的快照，采用快照副本的方式保留PV/PVC的状态。

通过查询Pod的Volume Mounts检查所有正在使用的PV/PVC卷。
将未使用的PV/PVC快照识别为孤立卷，并在Kubernetes资源清单中报告它们。
按需删除或重建PV/PVC卷。
使用Kubernetes Volume Snapshotter作为工具，可以方便和快速地查找和报告孤立卷，并且通过备份快照来避免数据丢失。该解决方案为Kubernetes集群的管理和维护提供了良好的支持。

**Comment by qmhu** [comment]
> 可以使用Kubernetes Volume Snapshotter。Volume Snapshotter是一个Kubernetes插件，可以将PV/PVC卷的快照备份到Kubernetes集群中的持久存储中。该插件可以通过以下步骤来实现查找和报告孤立卷：
> 
> 使用Kubernetes Volume Snapshotter创建PV/PVC卷的快照，采用快照副本的方式保留PV/PVC的状态。
> 
> 通过查询Pod的Volume Mounts检查所有正在使用的PV/PVC卷。 将未使用的PV/PVC快照识别为孤立卷，并在Kubernetes资源清单中报告它们。 按需删除或重建PV/PVC卷。 使用Kubernetes Volume Snapshotter作为工具，可以方便和快速地查找和报告孤立卷，并且通过备份快照来避免数据丢失。该解决方案为Kubernetes集群的管理和维护提供了良好的支持。

这个任务是希望能够实现一个插件，而不是引入其他依赖。

**Comment by xiu111** [comment]
To find the orphan volumes in a Kubernetes cluster using the Crane open-source project, you can follow these steps:

1. Clone the Crane repository: Start by cloning the Crane repository from GitHub using the following command:
   ```
   git clone https://github.com/gocrane/crane.git
   ```

2. Install Crane: Follow the installation instructions provided in the Crane repository's README file to set up Crane in your environment. Make sure you have all the necessary prerequisites installed.

3. Configure Crane: Once Crane is installed, configure it to access your Kubernetes cluster. You can refer to the Crane documentation or README file for detailed instructions on how to configure Crane for your specific cluster.

4. Write a custom Crane plugin: Since finding orphan volumes is not a built-in feature in Crane, you'll need to write a custom plugin to achieve this. Create a new Go file, such as `orphan_volumes.go`, in the `plugins` directory of the Crane project.

5. Implement the plugin: In the `orphan_volumes.go` file, you'll need to implement the logic to list all volumes and check if any pods are using them. You can make use of the Kubernetes client library and its API to retrieve the necessary information. Here's a basic example to get you started:

   ```go
   package main

   import (
   	"fmt"
   	"log"

   	"github.com/gocrane/crane/api"
   	"github.com/gocrane/crane/executor"
   )

   func main() {
   	// Initialize Crane executor
   	executor := executor.NewDefaultExecutor()

   	// List all volumes
   	volumes, err := executor.GetVolumes()
   	if err != nil {
   		log.Fatal("Failed to get volumes:", err)
   	}

   	// Check if volumes are used by any pods
   	for _, volume := range volumes {
   		pods, err := executor.GetPodsByVolume(volume)
   		if err != nil {
   			log.Printf("Failed to get pods for volume %s: %v", volume.Name, err)
   			continue
   		}

   		if len(pods) == 0 {
   			// Volume is orphaned
   			fmt.Println("Orphan volume:", volume.Name)
   		}
   	}
   }
   ```

   This example uses the Crane executor to retrieve volumes and check if any pods are using them. If no pods are found for a volume, it's considered an orphan volume.

6. Build and run the plugin: Build the Crane project with your custom plugin using the following command:
   ```
   go build -o crane .
   ```

7. Run the plugin: Execute the Crane binary to run the plugin and find the orphan volumes in your Kubernetes cluster:
   ```
   ./crane plugin orphan_volumes
   ```

   The output will display the names of any orphan volumes that are found.

By following these steps, you can utilize the Crane open-source project to find orphan volumes in your Kubernetes cluster.
